package https.webservices_sabre_com.websvc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2016-08-04T19:58:16.988+05:30
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "https://webservices.sabre.com/websvc", name = "SessionCreatePortType")
@XmlSeeAlso({org.xmlsoap.schemas.ws._2002._12.secext.ObjectFactory.class, org.ebxml.namespaces.messageheader.ObjectFactory.class, org.w3._2000._09.xmldsig.ObjectFactory.class, org.opentravel.ota._2002._11.ObjectFactory.class, org.xmlsoap.schemas.soap.envelope.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SessionCreatePortType {

    @WebMethod(operationName = "SessionCreateRQ", action = "OTA")
    @WebResult(name = "SessionCreateRS", targetNamespace = "http://www.opentravel.org/OTA/2002/11", partName = "body")
    public org.opentravel.ota._2002._11.SessionCreateRS sessionCreateRQ(
        @WebParam(partName = "header", mode = WebParam.Mode.INOUT, name = "MessageHeader", targetNamespace = "http://www.ebxml.org/namespaces/messageHeader", header = true)
        javax.xml.ws.Holder<org.ebxml.namespaces.messageheader.MessageHeader> header,
        @WebParam(partName = "header2", mode = WebParam.Mode.INOUT, name = "Security", targetNamespace = "http://schemas.xmlsoap.org/ws/2002/12/secext", header = true)
        javax.xml.ws.Holder<org.xmlsoap.schemas.ws._2002._12.secext.Security> header2,
        @WebParam(partName = "body", name = "SessionCreateRQ", targetNamespace = "http://www.opentravel.org/OTA/2002/11")
        org.opentravel.ota._2002._11.SessionCreateRQ body
    );
}
